-- 问题定向表
CREATE TABLE IF NOT EXISTS problem_orientation (
    id INT AUTO_INCREMENT PRIMARY KEY,
    a VARCHAR(255) NOT NULL,
    b VARCHAR(255) NOT NULL,
    c VARCHAR(255) NOT NULL,
    d VARCHAR(255) NOT NULL,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 原理探究表
CREATE TABLE IF NOT EXISTS principle_exploration (
    id INT AUTO_INCREMENT PRIMARY KEY,
    a VARCHAR(255) NOT NULL,
    b VARCHAR(255) NOT NULL,
    c VARCHAR(255) NOT NULL,
    d VARCHAR(255) NOT NULL,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);